### ISSUE TITLE
Tests pass but the app doesnt work in the browser

### ISSUE THREAD

**Issue by Sillhouette** [learn-co-curriculum/react-simple-state-lab#15]
Students are able to get the tests to pass but the app doesn't display in the browser. 
I tried cloning the solution down to my system to test and that also did not work in the browser.

I don't have the bandwidth to look into it myself but if someone is able to check the recent PRs I know the lab has worked properly in the past, maybe they can locate the breaking change.

**Comment by yoshinator** [comment]
Fixed issue where genMatrix and genCell where not returning anything.
